name: CI

# Specify which Github events will trigger a CI build
on: push

# Define a single job build
jobs:
  build:
  
    runs-on: ubuntu-latest

    # Define steps
    steps:
    # checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v2

    # Set up Python env
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
     # Install deps
      - name: Install deps
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      # Run tests
      - name: Test with pytest
        run:
          pytest --cov-inflammation.models tests/test_models.py

